;
; Theldus's blog
; This is free and unencumbered software released into the public domain.
;

%define BLOG_TITLE      Theldus's blog
%define POST_AUTHOR     Davidson Francis
%define SITE_REPOSITORY theldus.github.io
%define SITE_URL        https://blog.theldus.moe
%define GIT_ACCOUNT     https://github.com/Theldus
%define GIT_SITE_REPO   GIT_ACCOUNT/SITE_REPOSITORY
%define GIT_DISC_LINK   GIT_SITE_REPO/discussions

; My personal links
%define FLICKR "https://www.flickr.com/photos/186981135@N08/"
%define YT_CHANNEL \
    "https://www.youtube.com/channel/UC9KQ_NpInSJiqMEC0Ip4BMA"
